version: '3'
services:
    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "MySQLRootPassw0rd123"
            MYSQL_USER: "simple_web_app_user"
            MYSQL_PASSWORD: "simplewebapppass"
            MYSQL_DATABASE: "simple_web_app"
        volumes:
            #path to database
            - ./mysqldb:/var/lib/mysql
            #path to entrypoint
            #- ./application:/code
        #entrypoint: /code/mysqlentrypoint.sh
        networks:
            - webnet-dev
    php-fpm:
        build: ./dockerfiles/php-fpm
        volumes:
            - ./application:/code
#            - ./temp:/tmp
#            - ./dockerfiles/php-fpm/entrypoint.sh:/code/entrypoint.sh
        entrypoint: /code/entrypoint.sh
        networks:
            - webnet-dev
    nginx:
        image: nginx:1.17.8-alpine
#        build: ./dockerfiles/nginx
        networks:
            - webnet-dev
        ports: 
            - "8888:80"
        volumes:
            - ./application:/code
            - ./application/test.conf:/etc/nginx/conf.d/test.conf
networks:
    webnet-dev: