version: '3'
services:
    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "MySQLRootPassw0rd123"
        volumes:
            #path to database
            - ./mysqldb:/var/lib/mysql
        networks:
            - webnet-dev
    php-fpm:
        build: ./dockerfiles/php-fpm
        volumes:
            - ./application:/code
            - ./temp:/tmp
#            - ./dockerfiles/php-fpm/entrypoint.sh:/code/entrypoint.sh
#        entrypoint: /code/entrypoint.sh
        networks:
            - webnet-dev
    nginx:
        image: nginx:1.17.7-alpine
#        build: ./dockerfiles/nginx
        networks:
            - webnet-dev
        ports: 
            - "8888:80"
        volumes:
            - ./application:/code
            - ./nginx_datastore/test.conf:/etc/nginx/conf.d/test.conf
networks:
    webnet-dev: